[MODEXPS-37] - Added new export types
folio-org/mod-data-export-spring pull request #123
Opened 2021-11-16 12:55 UTC by Dmitriy-Butramyou

## Purpose
Add new export types
 - BATCH_VOUCHER_EXPORT
 - EDIFACT_ORDERS_EXPORT
 - ORDERS_EXPORT

## Approach
- Added new export types.
- Wrote the migration.

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-11-16 13:14 UTC, AndreiMPV requested changes

2021-11-16 13:14 UTC, AndreiMPV commented on src/main/resources/db/changelog/changes/db.changelog-4.1.0.xml
> +      ALTER TABLE diku_mod_data_export_spring.job rename COLUMN type TO _type;
Could you please remove hardcode of the schema name : "diku_mod_data_export_spring"

2021-11-16 13:14 UTC, AndreiMPV commented on src/main/resources/db/changelog/changes/db.changelog-4.1.0.xml
> +      CREATE TYPE ExportType AS enum ('CIRCULATION_LOG', 'BURSAR_FEES_FINES',
Can we do that without table recreation from scratch with old and new ExportTypes?

2021-11-16 13:19 UTC, AndreiMPV requested changes

2021-11-16 13:19 UTC, AndreiMPV commented on src/main/resources/db/changelog/changes/db.changelog-4.1.0.xml
> +<?xml version="1.1" encoding="UTF-8" standalone="no"?>
Can we replace this with SQL script?

2021-11-16 14:50 UTC, Dmitriy-Butramyou commented
Checked by the postman:
![image](https://user-images.githubusercontent.com/49509644/142007645-df34a8df-a6aa-4e46-94ca-c312752fa40a.png)
![image](https://user-images.githubusercontent.com/49509644/142007668-4c44dfbe-dcbf-4387-a933-c62d2ebf78bf.png)

2021-11-17 14:59 UTC, khandramai approved these changes

2021-11-18 07:19 UTC, AndreiMPV approved these changes

2021-11-19 07:37 UTC, merged